### PR TITLE
support app dns request via v2ray.

### PR DESCRIPTION
**Pull request by cyberblood**
change v2ray config and add some dns section.
add a iptables redirect scripts and a network monitor program to keeping iptables valid.

### CODE REVIEW

**Comment by chendefine** [comment]
Well done !  
I notice that the "v2ray-dns.keeper" is a binary file , whould you please show the sourcecode ?

**Comment by cyberblood** [comment]
yes, here is the sourcecode https://github.com/cyberblood/net_watcher

**Comment by chendefine** [comment]
Can you add "v2ray-dns.keeper" binary in arm and x86 arch please? Thanks !

**Comment by whyou** [comment]
Do we need to disable domain name sniffing after this change?

**Comment by cyberblood** [comment]
I think domain name sniffing is better. In fact, DNS redirection is not always working.

**Pull request merged**
